name: Update dependency version

on:
  repository_dispatch:
    types: [upstream-released]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependency:
    uses: dsanroman96/workflow-templates/.github/workflows/downstream-update.yml@main
    with:
      project_type: typescript
      upstream_name: ${{ github.event.client_payload.upstream }}
      version_tag: ${{ github.event.client_payload.version }}
